### ISSUE TITLE
Update "ptemcee" and "emcee"

### ISSUE THREAD

**Issue by mjwen** [openkim/kliff#127]
Hi @yonatank93, as discussed previously offline, we might need to udpdate "ptemcee" and "emcee". They are using very old `numpy` APIs that are not supported anymore. To move forward, e.g. using python3.10, we need to get these resolved. See a TODO in [setup.py](https://github.com/openkim/kliff/blob/30c50ffd095691ee3bf4b70a86d64993e3189355/setup.py#L104). 

I think since the package (I cannot remember which one of ptemcee" and "emcee") seems dead, I guess the easiest approach is to fork and fix it, then we make the forked on as the dependency. What do you think? 

If you can find other well-maintained packages that provide the same functionality, we can switch to them as well.

**Comment by yonatank93** [comment]
emcee is still well maintained, but ptemcee is not (the owner says that in the repo). I agree that maybe the best option is to fork it. I have my own fork that works, but I think we should fork it in openkim. I don't think I have access to do that, though.

**Comment by mjwen** [comment]
It would be fine to use the one in your github account. If it is updated, we can switch to using yours as the dependency.

**Comment by yonatank93** [comment]
What I have in my github account is a minimum update on ptemcee. Basically I just fix the problem with using np.float. Here is the link to my fork: https://github.com/yonatank93/ptemcee/tree/enhance_v1.0.0

**Comment by mjwen** [comment]
@yonatank93 can you please make a PR to make your version of ptemcee a dependency instead of the original one? Then we can be able use new version of python. Thanks !

**Comment by mjwen** [comment]
Fixed in #137
