### ISSUE TITLE
Bug in Neighbors

### ISSUE THREAD

**Issue by wilsonnater** [openkim/kliff#37]
In kliff.neighbor NeighborList, it appears there is some bug when isolated atoms are aligned an axis, such as the atoms being at 3,3,3 and 4,3,3. It cannot find neighbors then and it will crash with Segmentation fault (core dumped) if the atoms where at 3,3,3 and 4,4,3. I have attached a script that reproduces this issue.

[KliffBugTest.txt](https://github.com/openkim/kliff/files/8163361/KliffBugTest.txt)

**Comment by mjwen** [comment]
Hi @wilsonnater thanks for the bug report and the example script! 

I confirm that I can reproduce what you've described in the script. We'll look into it and get back to you soon.

**Comment by mjwen** [comment]
Hi @wilsonnater I've fixed the bug and please see #38 for more. 

It's in the master branch now if you want to try it out. I'll release a new version to PyPI and conda-forge soon.

**Comment by wilsonnater** [comment]
That fixed it on my side too.
